### PR TITLE
Fix stopping trace server during shutdown

### LINKED ISSUE #13: Trace Server not stopped when deactivating extension during shutdown
The trace server is not stopped when running this extension with vscode/codium remote. I have noticed this behaviour in local install as well, but very rarely. 

 I did some investigation and with some logging (to file) I was able to confirm, that the `deactivate()` method of the `vscode-trace-server` is being called. However, the call to `tree-kill(pid)` has no effect. More investigation needed to fix stopping the trace server on exit.

I did some more digging to figure out what's going on. I think what's happening is that VsCode exits before the `treeKill()` command is executed. `treeKill()` spawns external processes to get all the children pids from the parent pid of the trace server launcher. It reads the stdout of the command `ps -o pid --no-headers --ppid $ppid` and then uses the collected list of pids to call process.kill on it. This is done in a callback, but the parent VsCode application already exited and the hence the no process is killed. I was able to make it work by adding some async/wait/timeout call to delay the execution. 

Please note that this can also happen in the local case. I guess, that the shutdown of a local VsCode application takes longer than closing the remote processes.

_Originally posted by @bhufmann in https://github.com/eclipse-cdt-cloud/vscode-trace-extension/issues/173#issuecomment-1677871724_

### PR DESCRIPTION
**Pull request by bhufmann**
During shutdown of vscode and the triggered deactivation of the extension, the vscode services are not reliably available anymore. Hence the killing of the trace server process has to happen in the same thread of execution. The trace server is killed by calling  `treeKill` because the Trace Compass server spawns 2 processes. `treeKill` collects all processes starting from the parent PID using operation system specific calls. Once all PIDs are collected, each one is killed one by one asynchronously. The main execution continues and the callbacks to kill is not handled anymore. This is why the server continues. 

This patch calls `treeKill` right away and adds a delay before returning the shutdown procedure. This delay gives the `treeKill` execution time to finish.

Fixes #13

### CODE REVIEW

File: src/trace-server.ts [hunk 1]
```diff
@@ -71,11 +72,30 @@ export class TraceServer {
...
+
+            // Try to reset pid in workspace state
+            await context?.workspaceState.update(key, none);
+        }
+    }
+
     async startIfStopped(context: vscode.ExtensionContext | undefined) {
+        
         const pid = context?.workspaceState.get(key);
+        console.log("Pid: " + pid);
```
Comment (hriday-panchasara) [inline src/trace-server.ts:96]: Do we need this console statement?

**Review by hriday-panchasara — APPROVED** [review]
Works as expected. Tested in local as well as in remote with https://github.com/eclipse-cdt-cloud/vscode-trace-extension/pull/173. Server shuts down as soon as remote connection is closed. Thanks!

File: src/trace-server.ts (hunk 1 above)
Comment (bhufmann) [reply src/trace-server.ts:96]: no that should be gone
